config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  
  devise_for :users
  
  resources :campaigns do
    collection do
      get :search_organizations
    end
    resources :expenses
    resources :tasks do
      patch :update_status, on: :member
    end
  end

  resources :organizations do
    resources :contacts
  end

  resources :documents do
    resources :signatures
  end

  get 'signatures/:external_id/review' => 'signatures#review', as: :review_signature
  put 'signatures/:external_id/sign' => 'signatures#sign', as: :sign_signature
  
  if Rails.env.development?
    get 'prototypes' => 'prototypes#index'
    get 'prototypes/*path' => 'prototypes#show'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :user
  
  has_many :promotions, dependent: :destroy
  has_many :campaigns, through: :promotions, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :tasks, through: :campaigns
  
  validates :name, :status, presence: true

  enum :status, { active: 0, inactive: 1 }
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[show edit update destroy]

  def index
    @organizations = current_user.organizations
  end

  def show; end

  def new
    @organization = Organization.new
  end

  def edit; end

  def create
    @organization = Organization.new(organization_params)
    
    if @organization.save
      redirect_to @organization, success: success_message(@organization, :created)
    else
      flash_error_message
      render :new
    end
  end

  def update
    if @organization.update(organization_params)
      redirect_to @organization, success: success_message(@organization, :updated)
    else
      flash_error_message
      render :edit
    end
  end

  def destroy
    @organization.destroy

    redirect_to organizations_url, success: success_message(@organization, :destroyed)
  end

  private

  def set_organization
    @organization = Organization.find(params[:id])
  end

  def organization_params
    params.require(:organization)
          .permit(:name, :address, :address2, :city, :state, :zipcode, :phone, :status, campaign_ids: []).tap do |organization|
      organization[:user] = current_user
      organization[:campaigns] = Campaign.where(id: organization[:campaign_ids])
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
  def cancel_organization_link(organization)
    link_to :Cancel,
            (organization.new_record? ? organizations_path : organization),
            class: :secondary
  end
end

app/views/organizations/_form.html.erb
<%= form_with model: @organization, data: { turbo: false } do |f| %>
  <fieldset class="form-group">
    <div class="form-row">
      <%= f.label :status, "Enabled", class: "form-label required" %>
      <%= f.select :status, { Active: "active", Inactive: "inactive"}, {}, class: 'form-input' %>
    </div>

    <div class="form-row">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, class: "form-input" %>
    </div>
    
    <div class="form-row">
      <%= f.label :phone, "Phone Number", class: "form-label" %>
      <%= f.phone_field :phone, class: "form-input" %>
    </div>
    
    <div class="form-row">
      <%= f.label :address, class: "form-label" %>
      <%= f.text_field :address, class: "form-input" %>
    </div>

    <div class="form-row">
      <%= f.label :address2, class: "form-label" %>
      <%= f.text_field :address2, class: "form-input" %>
    </div>

    <div class="form-row">
      <%= f.label :city, class: "form-label" %>
      <%= f.text_field :city, class: "form-input" %>
    </div>

    <div class="form-row">
      <%= f.label :state, class: "form-label" %>
      <%= f.text_field :state, class: "form-input" %>
    </div>

    <div class="form-row">
      <%= f.label :zipcode, "Zip Code", class: "form-label" %>
      <%= f.text_field :zipcode, class: "form-input" %>
    </div>

    <div class="actions">
      <%= f.submit class: :primary %>
      <%= cancel_organization_link(@organization) %>
    </div>
  </fieldset>
<% end %>

app/views/organizations/_organization.html.erb
<tr id="<%= dom_id organization %>">
  <td headers="name-header">
    <%= link_to organization.name, organization, aria: { label: "View details for #{organization.name}" } %>
  </td>
  <td headers="location-header">
    <%= organization.city %>, <%= organization.state %>
  </td>
  <td headers="phone-header">
    <%= phone_to organization.phone, organization.phone %>
  </td>
  <td headers="created-header">
    <%= organization.created_at.iso8601 %>
  </td>
</tr>

app/views/organizations/_search_results.html.erb
<% organizations.each do |org| %>
  <div class="organization-result" 
       data-action="click->organization-selector#select"
       data-organization-id="<%= org.id %>"
       data-organization-name="<%= org.name %>">
    <%= org.name %>
  </div>
<% end %> 

app/views/organizations/edit.html.erb
<% content_for :title, "Edit Organization" %>

<div class="page-container">
  <header class="page-header">
    <h1>Edit <%= @organization.name %></h1>
  </header>

  <main class="form-container">
    <%= render 'form' %>
  </main>
</div>

app/views/organizations/index.html.erb
<% content_for :title, "Organizations" %>

<header class="page-header">
  <h1>Organizations</h1>
  <div class="subheader">
    <p>Manage organizations.</p>
    <nav class="nav-links">
      <ul class="links">
        <li class="nav-item">
          <%= link_to 'New Organization', new_organization_path %>
        </li>
      </ul>
    </nav>
  </div>
</header>

<main class="table-responsive">
  <table class="table" id="organizations">
    <thead>
      <tr>
        <th id="name-header" scope="col">Name</th>
        <th id="location-header"  scope="col">City, State</th>
        <th id="phone-header">Phone</th>
        <th id="created-header">Created At</th>
      </tr>
    </thead>
    <tbody>
      <%= render @organizations %>
    </tbody>
  </table>
</main>

app/views/organizations/new.html.erb
<% content_for :title, "New Organization" %>

<div class="page-container">
  <header class="page-header">
    <h1>Create a New Organization</h1>
  </header>

  <main class="form-container">
    <%= render 'form' %>
  </main>
</div>

app/views/organizations/show.html.erb
<% content_for :title, @organization.name %>

<main class="page-container">
  <header class="page-header">
    <h1><%= @organization.name %></h1>
    
    <div class="subheader">
      <div class="organization-status">
        <span class="badge <%= @organization.active? ? 'badge-enabled' : 'badge-disabled' %>">
          <%= @organization.active? ? 'Active' : 'Inactive' %>
        </span>
      </div>

      <nav class="nav-links">
        <ul class="links">
          <li class="nav-item"><%= link_to "All Organizations", organizations_path %></li>
          <li class="nav-item"><%= link_to :Edit, edit_organization_path(@organization) %></li>
          <li class="nav-item"><%= button_to :Delete, @organization, class: :link, data: { turbo_confirm: t('form.confirmation') }, method: :delete %></li>
        </ul>
      </nav>
    </div>
    
  </header>

  <section class="organization-details">
    <div class="organization-contact">
      <h2>Contact Information</h2>
      <address>
        <strong>Address:</strong>
        <div class="address-line"><%= @organization.address %></div>
        <% if @organization.address2.present? %>
          <div class="address-line"><%= @organization.address2 %></div>
        <% end %>
        <div class="address-line">
          <%= @organization.city %> <%= ", #{@organization.state}" if @organization.state.present? %> <%= @organization.zipcode %>
        </div>
        <div class="phone">
          <strong>Phone:</strong>
          <a href="tel:<%= @organization.phone %>">
            <%= number_to_phone(@organization.phone, area_code: true) %>
          </a>
        </div>
      </address>
    </div>

    <div class="organization-metadata">
      <h2>Additional Information</h2>
      <dl>
        <div class="metadata-item">
          <dt>Created</dt>
          <dd><time datetime="<%= @organization.created_at.iso8601 %>">
            <%= l(@organization.created_at, format: :long) %>
          </time></dd>
        </div>
        <div class="metadata-item">
          <dt>Last Updated</dt>
          <dd><time datetime="<%= @organization.updated_at.iso8601 %>">
            <%= l(@organization.updated_at, format: :long) %>
          </time></dd>
        </div>
      </dl>
    </div>
  </section>

   <section class="campaigns-list">
    <header class="page-header">
      <h2>Campaigns</h2>
      <div class="subheader">
        <p>Manage campaigns.</p>
        <span class="nav-links">
          <ul class="links">
            <li class="nav-item">
              <%= link_to "Add Campaign", new_campaign_path %>
            </li>
          </ul>
        </span>
      </div>
    </header>

    <div class="table-responsive">
      <table class="table" id="contacts">
        <thead>
          <tr>
            <th id="name-header" scope="col">Name</th>
          </tr>
        </thead>
        <tbody>
          <%= render @organization.campaigns %>
        </tbody>
      </table>
    </div>
  </section>

  <section class="contacts-list">
    <header class="page-header">
      <h2>Contacts</h2>
      <div class="subheader">
        <p>Manage contacts.</p>
        <span class="nav-links">
          <ul class="links">
            <li class=="nav-item">
              <%= link_to "Add Contact", new_organization_contact_path(@organization) %>
            </li>
          </ul>
        </span>
      </div>
    </header>

    <div class="table-responsive">
      <table class="table" id="contacts">
        <thead>
          <tr>
            <th id="name-header" scope="col">Name</th>
            <th id="email-header"  scope="col">Email</th>
            <th id="phone-header"  scope="col">Phone</th>
          </tr>
        </thead>
        <tbody>
          <%= render @organization.contacts %>
        </tbody>
      </table>
    </div>
  </section>
</main>